### ISSUE TITLE
Rework Playtime UI in Game View

### ISSUE THREAD

**Issue by Alfagun74** [Phalcode/crackpipe-app#10]
The Current Playtime and Avg. Playtimes are displayed very cluttered.

![Image](https://github.com/Phalcode/crackpipe-app/assets/22225051/8c8af0a9-6faa-496c-a227-9d5ef9abf218)

A better way to show the avg. and current playtime would be this:

![Image](https://github.com/Phalcode/crackpipe-app/assets/22225051/c0efba30-4130-4523-952b-16ab1d51458f)

**Comment by Yelo420** [comment]
![image](https://github.com/Phalcode/crackpipe-app/assets/88632464/e26a4d36-70e2-498f-8b7b-184295dd3e03)
@Alfagun74 Something like this?

**Comment by Alfagun74** [comment]
Love this placement ![Screenshot_2023-07-09-13-47-00-319-edit_com.android.chrome.jpg](https://github.com/Phalcode/crackpipe-app/assets/22225051/ccf3f78a-a056-4a96-86f9-49ae8e67aef3)

**Comment by Alfagun74** [comment]
Love this placement ![Screenshot_2023-07-09-13-47-00-319-edit_com.android.chrome.jpg](https://github.com/Phalcode/crackpipe-app/assets/22225051/ccf3f78a-a056-4a96-86f9-49ae8e67aef3)

**Comment by Yelo420** [comment]
@Alfagun74 
![image](https://github.com/Phalcode/crackpipe-app/assets/88632464/01a05db1-f33c-44da-b037-e2416e24bdd9)

A first draft directly in the UI. What do you say to the sizes, distances? I also made the status combobox a bit smaller in height. Should there be a slightly transparent field around the times? Does anything else bother you, or do you notice anything else?

**Comment by Alfagun74** [comment]
I believe it appears quite nice.
- Perhaps adjusting the positioning of the "last played" feature slightly towards the center would create better alignment.
- The smaller combobox is visually better.
- I don't think a background is necessary for the times since the existing darkened background should be enough contrast. Can you please verify if the text remains readable on light backgrounds?

**Comment by Yelo420** [comment]
@Alfagun74 
I think the average symbol fits optically better (cause then all texts are about the same length) and is more understandable.
I will adjust the position.

**Comment by Yelo420** [comment]
@Alfagun74 
![image](https://github.com/Phalcode/crackpipe-app/assets/88632464/ad2a5b3a-d7d1-4c29-9ace-aa802166d32f)
Then this is the final result for the change
